name: Ruby

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.146.0
        with:
          ruby-version: 2.7.8
          bundler-cache: true
      - name: Run Rubocop
        run: bundle exec rubocop --force-exclusion
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.146.0
        with:
          ruby-version: 2.7.8
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
